<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGwnxzc3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGwnxzc3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGwnxzc3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGwnxzc3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGwnxzc3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Gwnxzc3',
    'container.build_id' => '636d5fa3',
    'container.build_time' => 1589464792,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGwnxzc3');
